Update READMEs of text-image sample app
vespa-engine/sample-apps pull request #765
Opened 2021-11-29 08:06 UTC by lesters

@kkraune @thigm85 Please review.

2021-11-29 11:06 UTC, thigm85 requested changes

2021-11-29 11:06 UTC, thigm85 commented on text-image-search/src/python/README.md
> +download the data, our manually from from [the Kaggle
typo: or manually from

2021-11-29 11:06 UTC, thigm85 commented on text-image-search/src/python/README.md
> +Notebook](https://github.com/vespa-engine/sample-apps/blob/master/text-image-search/src/python/compare-pre-trained-clip-for-text-image-search.ipynb)
I think we can do `src/python/compare-pre-trained-clip-for-text-image-search.ipynb`?

2021-11-30 08:23 UTC, merged

2021-11-30 08:48 UTC, kkraune reviewed
👍